name: Bug Report
description: If you encounter an issue whilst using our app, please use this template to help improve the app.
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug you encountered. Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can do it ourselves.
      placeholder: Tell us how you did it
      value: "1. Clicked on..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: |
        Examples:
          - **OS**: Ubuntu 20.04
          - **App Version** and/or **Commit ID**: 1.0.0 c9d43be
        
        To find app version, Cider Menu -> About
      value: |
        - OS:
        - App Version and/or Commit ID:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: checkboxes
    id: disclaimer
    attributes:
      label: Disclaimer
      description: By submitting this issue, you are aware of our [Support Disclaimer](https://docs.cider.sh/support/disclaimer) and acknowledge that your issue may be immidiately closed if it is invalid.
      options:
        - label: I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)
          required: true
